### PR TITLE
Feature/modal

### PR DESCRIPTION
**Pull request by jonkim204**
Added working modal for add product/shave button

### CODE REVIEW

**Comment by kylebowen** [comment]
build seems to be failing because the ImageUpload component is defined but not used in the shave and product forms and so the build fails to compile. When I try to add the component into the forms, I get errors when attempting to use it. Not sure if that's a config issue on my end or something going on in the component. Might need to have @richart14 take a look at this to make sure it's a config issue and not something else?

**Comment by dghero** [comment]
This branch is working for me, and I found the following issues

ADD PRODUCT MODAL:
-1) Modal does not automatically close on submit
-2) After closing the modal and opening it up again, the Nickname field retains its original input data. Proceeding to type in either the Brand or Model fields will only overwrite that field's section of the username (perhaps reinitialize Brand and Model both as blank when opening the modal?)
-3) Collection page does not update upon successful submission of new product; to view the new product, user must currently navigate away from the page and back to see it


ADD SHAVE MODAL:
-1) Submitted dates read as 1 day earlier than 


EDIT SHAVE:
-0) CRITICAL: Opens up a form called "Add Shave". Submission of this form does nothing (does not update the item that called it, does not create a new shave)

The following were problems at commit (9cb4411):
-1) IMPORTANT: Most any unmodified field (except date) will appear to be fine at first. However, navigating away from the shaves page and returning will show all unmodified fields have been reset to blank.
-2) Date Field does not prepoulate with original date. Overwrites original date to today's date if untouched.
-3) Additional Care does not prepopulate with original product. Appears to preserve the field data, but see (1)
-4) Missing "Share" checkbox field

**Comment by richart14** [comment]
@kylebowen what is the error that you are getting. There is some configuring of your `.env` file to added the authorizations for logging into cloudinary.

**Comment by kylebowen** [comment]
@richart14 The error I had earlier was my own mistake- I forgot to `npm install` on my server after the cloudinary update, so it was erroring out there and the client was receiving an unexpected type of response.

**Pull request merged**
